// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/q_a_engine.proto

package qaenginepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string               `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Email                string               `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	IsActive             bool                 `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsAdmin              bool                 `protobuf:"varint,8,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8db5030c5c5888df, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *User) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8db5030c5c5888df, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8db5030c5c5888df, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "qaengine.User")
	proto.RegisterType((*CreateUserRequest)(nil), "qaengine.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "qaengine.CreateUserResponse")
}

func init() {
	proto.RegisterFile("proto/q_a_engine.proto", fileDescriptor_8db5030c5c5888df)
}

var fileDescriptor_8db5030c5c5888df = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x14, 0xc4, 0x4d, 0xec, 0x9f, 0xe4, 0x15, 0x8a, 0x2e, 0x22, 0x31, 0x55, 0x0c, 0x39, 0xe5, 0x94,
	0x42, 0x3d, 0xa8, 0x78, 0x8a, 0x9e, 0xbc, 0x78, 0x88, 0x0a, 0xe2, 0x25, 0x6c, 0x9b, 0xd7, 0xb2,
	0xd0, 0xfc, 0x69, 0x76, 0x53, 0xbf, 0xa5, 0x9f, 0x49, 0xf6, 0xa5, 0x4b, 0x05, 0x05, 0x3d, 0xce,
	0xfc, 0x66, 0x76, 0x93, 0x59, 0x38, 0xad, 0x9b, 0x4a, 0x55, 0xd3, 0x4d, 0xc6, 0x33, 0x2c, 0x57,
	0xa2, 0xc4, 0x98, 0x0c, 0xe6, 0x6c, 0x78, 0xa7, 0xfd, 0xcb, 0x55, 0x55, 0xad, 0xd6, 0x38, 0x25,
	0x7f, 0xde, 0x2e, 0xa7, 0x4a, 0x14, 0x28, 0x15, 0x2f, 0xea, 0x2e, 0x1a, 0x7e, 0xda, 0xd0, 0x7b,
	0x95, 0xd8, 0xb0, 0x31, 0xd8, 0x22, 0xf7, 0xac, 0xc0, 0x8a, 0xfa, 0xa9, 0x2d, 0x72, 0x76, 0x01,
	0xb0, 0x14, 0x8d, 0x54, 0x59, 0xc9, 0x0b, 0xf4, 0xec, 0xc0, 0x8a, 0xdc, 0xd4, 0x25, 0xe7, 0x89,
	0x17, 0xc8, 0x26, 0xe0, 0xae, 0xb9, 0xa1, 0x87, 0x44, 0x1d, 0x6d, 0x10, 0xf4, 0xc1, 0x69, 0x25,
	0x36, 0xc4, 0x7a, 0x1d, 0x33, 0x9a, 0x9d, 0x40, 0x1f, 0x0b, 0x2e, 0xd6, 0x5e, 0x9f, 0x40, 0x27,
	0x74, 0xa3, 0xe6, 0x52, 0x7e, 0x54, 0x4d, 0xee, 0x0d, 0xba, 0x86, 0xd1, 0xfa, 0x2a, 0x21, 0x33,
	0xbe, 0x50, 0x62, 0x8b, 0xde, 0x30, 0xb0, 0x22, 0x27, 0x75, 0x84, 0x4c, 0x48, 0xb3, 0x33, 0x70,
	0x34, 0xcc, 0x0b, 0x51, 0x7a, 0x0e, 0xb1, 0xa1, 0x90, 0x89, 0x96, 0xec, 0x16, 0x60, 0xd1, 0x20,
	0x57, 0x98, 0x67, 0x5c, 0x79, 0x6e, 0x60, 0x45, 0xa3, 0x99, 0x1f, 0x77, 0x83, 0xc4, 0x66, 0x90,
	0xf8, 0xc5, 0x0c, 0x92, 0xba, 0xbb, 0x74, 0xa2, 0x74, 0xb5, 0xad, 0x73, 0x53, 0x85, 0xbf, 0xab,
	0xbb, 0x74, 0xa2, 0xc2, 0x6b, 0x38, 0x7e, 0xa0, 0x73, 0xf4, 0xaa, 0x29, 0x6e, 0x5a, 0x94, 0x8a,
	0x85, 0xd0, 0xd3, 0x03, 0xd0, 0xbc, 0xa3, 0xd9, 0x38, 0x36, 0xef, 0x13, 0x53, 0x88, 0x58, 0x78,
	0x03, 0xec, 0x7b, 0x51, 0xd6, 0x55, 0x29, 0xf1, 0x3f, 0xcd, 0xd9, 0x1b, 0x8c, 0xb4, 0x7a, 0xc6,
	0x66, 0x2b, 0x16, 0xc8, 0x1e, 0x01, 0xf6, 0x07, 0xb1, 0xc9, 0xbe, 0xf2, 0xe3, 0xbb, 0xfc, 0xf3,
	0xdf, 0x61, 0x77, 0x77, 0x78, 0x70, 0xcf, 0xde, 0x8f, 0xe8, 0x6f, 0xef, 0x4c, 0xac, 0x9e, 0xcf,
	0x07, 0xe4, 0x5c, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xe2, 0x1b, 0x37, 0x7d, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/qaengine.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qaengine.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qaengine.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/q_a_engine.proto",
}
