// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_service_message.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string               `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Email                string               `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	IsActive             bool                 `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsAdmin              bool                 `protobuf:"varint,8,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *User) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindUserRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserRequest) Reset()         { *m = FindUserRequest{} }
func (m *FindUserRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserRequest) ProtoMessage()    {}
func (*FindUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{3}
}

func (m *FindUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserRequest.Unmarshal(m, b)
}
func (m *FindUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserRequest.Marshal(b, m, deterministic)
}
func (m *FindUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserRequest.Merge(m, src)
}
func (m *FindUserRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserRequest.Size(m)
}
func (m *FindUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserRequest proto.InternalMessageInfo

func (m *FindUserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserResponse) Reset()         { *m = FindUserResponse{} }
func (m *FindUserResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserResponse) ProtoMessage()    {}
func (*FindUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{4}
}

func (m *FindUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserResponse.Unmarshal(m, b)
}
func (m *FindUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserResponse.Marshal(b, m, deterministic)
}
func (m *FindUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserResponse.Merge(m, src)
}
func (m *FindUserResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserResponse.Size(m)
}
func (m *FindUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserResponse proto.InternalMessageInfo

func (m *FindUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{5}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	IsUpdated            bool     `protobuf:"varint,1,opt,name=is_updated,json=isUpdated,proto3" json:"is_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{6}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetIsUpdated() bool {
	if m != nil {
		return m.IsUpdated
	}
	return false
}

type DeleteUserRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{7}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteUserResponse struct {
	IsDeleted            bool     `protobuf:"varint,1,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{8}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type ChangePasswordRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OldPassword          string   `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	RetypeNewPassword    string   `protobuf:"bytes,4,opt,name=retype_new_password,json=retypeNewPassword,proto3" json:"retype_new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{9}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetRetypeNewPassword() string {
	if m != nil {
		return m.RetypeNewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	IsPasswordChanged    bool     `protobuf:"varint,1,opt,name=is_password_changed,json=isPasswordChanged,proto3" json:"is_password_changed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{10}
}

func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func (m *ChangePasswordResponse) GetIsPasswordChanged() bool {
	if m != nil {
		return m.IsPasswordChanged
	}
	return false
}

type ToggleAdminRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleAdminRequest) Reset()         { *m = ToggleAdminRequest{} }
func (m *ToggleAdminRequest) String() string { return proto.CompactTextString(m) }
func (*ToggleAdminRequest) ProtoMessage()    {}
func (*ToggleAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{11}
}

func (m *ToggleAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleAdminRequest.Unmarshal(m, b)
}
func (m *ToggleAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleAdminRequest.Marshal(b, m, deterministic)
}
func (m *ToggleAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleAdminRequest.Merge(m, src)
}
func (m *ToggleAdminRequest) XXX_Size() int {
	return xxx_messageInfo_ToggleAdminRequest.Size(m)
}
func (m *ToggleAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleAdminRequest proto.InternalMessageInfo

func (m *ToggleAdminRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ToggleAdminResponse struct {
	IsUpdated            bool     `protobuf:"varint,1,opt,name=is_updated,json=isUpdated,proto3" json:"is_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleAdminResponse) Reset()         { *m = ToggleAdminResponse{} }
func (m *ToggleAdminResponse) String() string { return proto.CompactTextString(m) }
func (*ToggleAdminResponse) ProtoMessage()    {}
func (*ToggleAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{12}
}

func (m *ToggleAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleAdminResponse.Unmarshal(m, b)
}
func (m *ToggleAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleAdminResponse.Marshal(b, m, deterministic)
}
func (m *ToggleAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleAdminResponse.Merge(m, src)
}
func (m *ToggleAdminResponse) XXX_Size() int {
	return xxx_messageInfo_ToggleAdminResponse.Size(m)
}
func (m *ToggleAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleAdminResponse proto.InternalMessageInfo

func (m *ToggleAdminResponse) GetIsUpdated() bool {
	if m != nil {
		return m.IsUpdated
	}
	return false
}

type ToggleActiveRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleActiveRequest) Reset()         { *m = ToggleActiveRequest{} }
func (m *ToggleActiveRequest) String() string { return proto.CompactTextString(m) }
func (*ToggleActiveRequest) ProtoMessage()    {}
func (*ToggleActiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{13}
}

func (m *ToggleActiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleActiveRequest.Unmarshal(m, b)
}
func (m *ToggleActiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleActiveRequest.Marshal(b, m, deterministic)
}
func (m *ToggleActiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleActiveRequest.Merge(m, src)
}
func (m *ToggleActiveRequest) XXX_Size() int {
	return xxx_messageInfo_ToggleActiveRequest.Size(m)
}
func (m *ToggleActiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleActiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleActiveRequest proto.InternalMessageInfo

func (m *ToggleActiveRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ToggleActiveResponse struct {
	IsUpdated            bool     `protobuf:"varint,1,opt,name=is_updated,json=isUpdated,proto3" json:"is_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleActiveResponse) Reset()         { *m = ToggleActiveResponse{} }
func (m *ToggleActiveResponse) String() string { return proto.CompactTextString(m) }
func (*ToggleActiveResponse) ProtoMessage()    {}
func (*ToggleActiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83213d866ee4d08a, []int{14}
}

func (m *ToggleActiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleActiveResponse.Unmarshal(m, b)
}
func (m *ToggleActiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleActiveResponse.Marshal(b, m, deterministic)
}
func (m *ToggleActiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleActiveResponse.Merge(m, src)
}
func (m *ToggleActiveResponse) XXX_Size() int {
	return xxx_messageInfo_ToggleActiveResponse.Size(m)
}
func (m *ToggleActiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleActiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleActiveResponse proto.InternalMessageInfo

func (m *ToggleActiveResponse) GetIsUpdated() bool {
	if m != nil {
		return m.IsUpdated
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "ranabd36.qaengine.User")
	proto.RegisterType((*CreateUserRequest)(nil), "ranabd36.qaengine.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "ranabd36.qaengine.CreateUserResponse")
	proto.RegisterType((*FindUserRequest)(nil), "ranabd36.qaengine.FindUserRequest")
	proto.RegisterType((*FindUserResponse)(nil), "ranabd36.qaengine.FindUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "ranabd36.qaengine.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "ranabd36.qaengine.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "ranabd36.qaengine.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "ranabd36.qaengine.DeleteUserResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "ranabd36.qaengine.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "ranabd36.qaengine.ChangePasswordResponse")
	proto.RegisterType((*ToggleAdminRequest)(nil), "ranabd36.qaengine.ToggleAdminRequest")
	proto.RegisterType((*ToggleAdminResponse)(nil), "ranabd36.qaengine.ToggleAdminResponse")
	proto.RegisterType((*ToggleActiveRequest)(nil), "ranabd36.qaengine.ToggleActiveRequest")
	proto.RegisterType((*ToggleActiveResponse)(nil), "ranabd36.qaengine.ToggleActiveResponse")
}

func init() {
	proto.RegisterFile("user_service_message.proto", fileDescriptor_83213d866ee4d08a)
}

var fileDescriptor_83213d866ee4d08a = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x55, 0xe1, 0x4e, 0xd4, 0x4c,
	0x14, 0xfd, 0xd8, 0x6f, 0x17, 0xba, 0x77, 0x09, 0xba, 0x03, 0x6a, 0xad, 0x31, 0x4a, 0x01, 0xc5,
	0x98, 0x94, 0x04, 0xd4, 0xc4, 0x5f, 0x8a, 0x18, 0xe3, 0x2f, 0x62, 0x56, 0xf8, 0xa3, 0x89, 0xcd,
	0xec, 0xce, 0x50, 0x27, 0xd9, 0x6d, 0x4b, 0xdb, 0x85, 0xf8, 0x30, 0x3e, 0x82, 0xaf, 0xe2, 0x33,
	0x79, 0x67, 0xa6, 0xb3, 0x6d, 0xb7, 0x85, 0x45, 0x7f, 0x10, 0x98, 0xb9, 0xe7, 0x9c, 0xb9, 0x73,
	0xe7, 0x9c, 0x02, 0xce, 0x34, 0xe5, 0x89, 0x8f, 0x3f, 0x17, 0x62, 0xc4, 0xfd, 0x09, 0x4f, 0x53,
	0x1a, 0x70, 0x2f, 0x4e, 0xa2, 0x2c, 0x22, 0xfd, 0x84, 0x86, 0x74, 0xc8, 0x0e, 0x5e, 0x79, 0xe7,
	0x94, 0x87, 0x81, 0x08, 0xb9, 0xf3, 0x28, 0x88, 0xa2, 0x60, 0xcc, 0xf7, 0x14, 0x60, 0x38, 0x3d,
	0xdb, 0xcb, 0x04, 0x72, 0x32, 0x3a, 0x89, 0x35, 0xc7, 0xfd, 0xdd, 0x82, 0xf6, 0x29, 0xca, 0x91,
	0x35, 0x68, 0x09, 0x66, 0x2f, 0x3d, 0x5e, 0xda, 0xed, 0x0c, 0xf0, 0x2f, 0xf2, 0x10, 0xe0, 0x4c,
	0x24, 0x69, 0xe6, 0x87, 0x74, 0xc2, 0xed, 0x16, 0xee, 0x77, 0x07, 0x5d, 0xb5, 0x73, 0x8c, 0x1b,
	0xe4, 0x01, 0x74, 0xc7, 0xd4, 0x54, 0xff, 0x57, 0x55, 0x4b, 0x6e, 0xa8, 0xa2, 0x03, 0x96, 0x6c,
	0x53, 0xd5, 0xda, 0xba, 0x66, 0xd6, 0x64, 0x03, 0x3a, 0x7c, 0x42, 0xc5, 0xd8, 0xee, 0xa8, 0x82,
	0x5e, 0x48, 0x46, 0x4c, 0xd3, 0xf4, 0x32, 0x4a, 0x98, 0xbd, 0xac, 0x19, 0x66, 0x2d, 0x8f, 0x12,
	0xa9, 0x4f, 0x47, 0x99, 0xb8, 0xe0, 0xf6, 0x0a, 0x16, 0xad, 0x81, 0x25, 0xd2, 0x43, 0xb5, 0x26,
	0xf7, 0xc1, 0x92, 0x45, 0x36, 0x11, 0xa1, 0x6d, 0xa9, 0xda, 0x0a, 0xd6, 0xe4, 0x92, 0xbc, 0x06,
	0x18, 0x25, 0x9c, 0x66, 0x9c, 0xf9, 0x34, 0xb3, 0xbb, 0x58, 0xec, 0xed, 0x3b, 0x9e, 0x1e, 0x88,
	0x67, 0x06, 0xe2, 0x9d, 0x98, 0x81, 0x0c, 0xba, 0x39, 0xfa, 0x30, 0x93, 0xd4, 0x69, 0xcc, 0x0c,
	0x15, 0x16, 0x53, 0x73, 0xf4, 0x61, 0xe6, 0xbe, 0x85, 0xfe, 0x91, 0xd2, 0x91, 0x53, 0x1d, 0xf0,
	0xf3, 0x29, 0x42, 0xc8, 0x73, 0x68, 0xcb, 0x01, 0xa8, 0xf1, 0xf6, 0xf6, 0xef, 0x79, 0xb5, 0x87,
	0xf2, 0x14, 0x5a, 0x81, 0xdc, 0x6d, 0x20, 0x65, 0x85, 0x34, 0x8e, 0xc2, 0x94, 0xcf, 0xbf, 0x8f,
	0xbb, 0x09, 0xb7, 0x3e, 0x88, 0x90, 0x95, 0x4f, 0x99, 0x87, 0xbc, 0x81, 0xdb, 0x05, 0x24, 0x97,
	0xf9, 0xab, 0x4e, 0xf0, 0x2e, 0xa7, 0xea, 0x62, 0xff, 0x7c, 0x97, 0x03, 0x20, 0x65, 0x85, 0xbc,
	0x09, 0xf4, 0x16, 0x3e, 0x5a, 0x3e, 0x33, 0x25, 0x64, 0x0d, 0xf0, 0x8d, 0x35, 0x92, 0xb9, 0x5b,
	0xd0, 0x7f, 0xcf, 0xc7, 0xbc, 0x7a, 0xec, 0xfc, 0xe5, 0x50, 0xb9, 0x0c, 0xaa, 0x28, 0x33, 0x55,
	0x28, 0x29, 0x6b, 0x24, 0x73, 0x7f, 0x2e, 0xc1, 0x9d, 0xa3, 0xef, 0x34, 0x0c, 0xf8, 0xa7, 0xdc,
	0x5d, 0x57, 0xc8, 0x93, 0x4d, 0x58, 0x8d, 0xc6, 0xcc, 0x9f, 0x99, 0x52, 0x07, 0xa0, 0x87, 0x7b,
	0x86, 0x29, 0x21, 0x21, 0xbf, 0x2c, 0x20, 0x3a, 0x05, 0x3d, 0xdc, 0x9b, 0x41, 0x3c, 0x58, 0x4f,
	0x78, 0xf6, 0x23, 0xe6, 0x7e, 0x05, 0xa9, 0x33, 0xd1, 0xd7, 0xa5, 0xe3, 0x02, 0xef, 0x7e, 0x84,
	0xbb, 0xf3, 0xed, 0xe5, 0x17, 0x43, 0x25, 0xbc, 0x98, 0x51, 0xf0, 0x47, 0x0a, 0x65, 0x6e, 0xd8,
	0x17, 0xa9, 0x21, 0x68, 0x3a, 0x93, 0x26, 0x3a, 0x89, 0x02, 0xb4, 0xab, 0xca, 0xc2, 0x55, 0x43,
	0x7c, 0x01, 0xeb, 0x15, 0xd4, 0xcd, 0xde, 0x67, 0x67, 0xc6, 0x52, 0x19, 0xbc, 0x4a, 0xfc, 0x25,
	0x6c, 0x54, 0x61, 0x37, 0x52, 0xdf, 0xff, 0xd5, 0x41, 0xd7, 0xe1, 0x9b, 0x7e, 0xd6, 0xdf, 0x38,
	0xf9, 0x0b, 0x3f, 0x4f, 0x5f, 0x01, 0x8a, 0x50, 0x90, 0xed, 0x06, 0xd7, 0xd5, 0x52, 0xe7, 0xec,
	0x2c, 0x40, 0xe9, 0x7e, 0xdc, 0xff, 0xc8, 0x29, 0x58, 0x26, 0x28, 0xc4, 0x6d, 0x20, 0xcd, 0x05,
	0xcd, 0xd9, 0xba, 0x16, 0x33, 0x93, 0xc5, 0x9e, 0x0b, 0xf3, 0x37, 0xf6, 0x5c, 0x4b, 0x57, 0x63,
	0xcf, 0xf5, 0x04, 0x69, 0xf1, 0xc2, 0xff, 0x8d, 0xe2, 0xb5, 0x0c, 0x35, 0x8a, 0xd7, 0x43, 0x84,
	0xe2, 0x01, 0xac, 0x55, 0x7d, 0x48, 0x76, 0x9b, 0x66, 0xd9, 0x94, 0x24, 0xe7, 0xd9, 0x0d, 0x90,
	0xb3, 0x83, 0xbe, 0x41, 0xaf, 0x64, 0x40, 0xd2, 0xd4, 0x60, 0xdd, 0xc6, 0xce, 0x93, 0x45, 0xb0,
	0x99, 0x3e, 0x85, 0xd5, 0xb2, 0x07, 0xc9, 0x35, 0xcc, 0xb2, 0x97, 0x9d, 0xa7, 0x0b, 0x71, 0xe6,
	0x88, 0x77, 0xed, 0x2f, 0xad, 0x78, 0x38, 0x5c, 0x56, 0xff, 0x15, 0x0e, 0xfe, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x96, 0x8c, 0xff, 0x77, 0xa0, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceServerClient is the client API for UserServiceServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceServerClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	FindUser(ctx context.Context, in *FindUserRequest, opts ...grpc.CallOption) (*FindUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	ToggleAdmin(ctx context.Context, in *ToggleAdminRequest, opts ...grpc.CallOption) (*ToggleAdminResponse, error)
	ToggleActive(ctx context.Context, in *ToggleActiveRequest, opts ...grpc.CallOption) (*ToggleActiveResponse, error)
}

type userServiceServerClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceServerClient(cc grpc.ClientConnInterface) UserServiceServerClient {
	return &userServiceServerClient{cc}
}

func (c *userServiceServerClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/ranabd36.qaengine.UserServiceServer/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceServerClient) FindUser(ctx context.Context, in *FindUserRequest, opts ...grpc.CallOption) (*FindUserResponse, error) {
	out := new(FindUserResponse)
	err := c.cc.Invoke(ctx, "/ranabd36.qaengine.UserServiceServer/FindUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceServerClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/ranabd36.qaengine.UserServiceServer/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceServerClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/ranabd36.qaengine.UserServiceServer/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceServerClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/ranabd36.qaengine.UserServiceServer/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceServerClient) ToggleAdmin(ctx context.Context, in *ToggleAdminRequest, opts ...grpc.CallOption) (*ToggleAdminResponse, error) {
	out := new(ToggleAdminResponse)
	err := c.cc.Invoke(ctx, "/ranabd36.qaengine.UserServiceServer/ToggleAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceServerClient) ToggleActive(ctx context.Context, in *ToggleActiveRequest, opts ...grpc.CallOption) (*ToggleActiveResponse, error) {
	out := new(ToggleActiveResponse)
	err := c.cc.Invoke(ctx, "/ranabd36.qaengine.UserServiceServer/ToggleActive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServerServer is the server API for UserServiceServer service.
type UserServiceServerServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	FindUser(context.Context, *FindUserRequest) (*FindUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	ToggleAdmin(context.Context, *ToggleAdminRequest) (*ToggleAdminResponse, error)
	ToggleActive(context.Context, *ToggleActiveRequest) (*ToggleActiveResponse, error)
}

// UnimplementedUserServiceServerServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServerServer struct {
}

func (*UnimplementedUserServiceServerServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServerServer) FindUser(ctx context.Context, req *FindUserRequest) (*FindUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUser not implemented")
}
func (*UnimplementedUserServiceServerServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServerServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserServiceServerServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedUserServiceServerServer) ToggleAdmin(ctx context.Context, req *ToggleAdminRequest) (*ToggleAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleAdmin not implemented")
}
func (*UnimplementedUserServiceServerServer) ToggleActive(ctx context.Context, req *ToggleActiveRequest) (*ToggleActiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleActive not implemented")
}

func RegisterUserServiceServerServer(s *grpc.Server, srv UserServiceServerServer) {
	s.RegisterService(&_UserServiceServer_serviceDesc, srv)
}

func _UserServiceServer_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServerServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranabd36.qaengine.UserServiceServer/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServerServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServiceServer_FindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServerServer).FindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranabd36.qaengine.UserServiceServer/FindUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServerServer).FindUser(ctx, req.(*FindUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServiceServer_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServerServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranabd36.qaengine.UserServiceServer/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServerServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServiceServer_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServerServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranabd36.qaengine.UserServiceServer/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServerServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServiceServer_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServerServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranabd36.qaengine.UserServiceServer/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServerServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServiceServer_ToggleAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServerServer).ToggleAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranabd36.qaengine.UserServiceServer/ToggleAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServerServer).ToggleAdmin(ctx, req.(*ToggleAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServiceServer_ToggleActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServerServer).ToggleActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ranabd36.qaengine.UserServiceServer/ToggleActive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServerServer).ToggleActive(ctx, req.(*ToggleActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserServiceServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ranabd36.qaengine.UserServiceServer",
	HandlerType: (*UserServiceServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserServiceServer_CreateUser_Handler,
		},
		{
			MethodName: "FindUser",
			Handler:    _UserServiceServer_FindUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserServiceServer_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserServiceServer_DeleteUser_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _UserServiceServer_ChangePassword_Handler,
		},
		{
			MethodName: "ToggleAdmin",
			Handler:    _UserServiceServer_ToggleAdmin_Handler,
		},
		{
			MethodName: "ToggleActive",
			Handler:    _UserServiceServer_ToggleActive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_service_message.proto",
}
